### ISSUE TITLE
State Machine Many Composites (Horizontal) in the sample app crashes sometimes

### ISSUE THREAD

**Issue by michaelkruglos** [Oaz/AvaloniaGraphControl#13]
State Machine Many Composites (Horizontal) in the sample app crashes sometimes. Exception comes from MSAGL. I'm using the latest version of MSAGL from github.

The crash doesn't happen every time I select this graph, but it happens often.

**Comment by Oaz** [comment]
Do you have any clue regarding the "sometimes"?
I know there are some causes of crash in MSAGL but the one I experienced are systematically reproducible as they are due to specific graph configurations.
In all cases, the issue shall probably be opened with MSAGL. I don't see what we can do right here.

**Comment by michaelkruglos** [comment]
Usually a second time I select it.
